#!/usr/bin/env php
<?php

/**
 * @file
 * Script to apply required recipes without completing installation.
 *
 * This allows users to experience an interactive installation with less
 * waiting.
 */

use Drupal\RecipeKit\Installer\Hooks;

$_GET['rewrite'] = 'ok';
$_GET['site_name'] = 'Drupal CMS';
$_GET['template'] = '1';

register_shutdown_function('_install_drupal_cms_profile_modules');

function _install_drupal_cms_profile_modules() {
  global $install_state;
  if ($install_state['base_system_verified']) {
    batch_set(Hooks::applyRecipes($install_state));
    $batch = &batch_get();
    $batch['progressive'] = FALSE;
    batch_process();
    \Drupal::state()->set('recipe_installer_kit.profile_modules_installed', TRUE);
  }
}

chdir(dirname(__DIR__) . '/web/core');
ob_start(fn($buffer, $phase) => TRUE, 1);
include 'install.php';
