#!/usr/bin/env php
<?php

/**
 * @file
 * Script to apply required recipes without completing installation.
 *
 * This allows users to experience an interactive installation with less
 * waiting.
 */

use Drupal\Core\Installer\Form\SiteConfigureForm;
use Drupal\RecipeKit\Installer\Hooks;

$_GET['rewrite'] = 'ok';
$_GET['name'] = '1';
$_GET['template'] = '1';

register_shutdown_function('_install_drupal_cms_profile_modules');

function _install_drupal_cms_profile_modules() {
  global $install_state;
  if (!empty($install_state['base_system_verified'])) {
    // Submit install_configure_form programmatically during the pre-run phase.
    $install_state['forms']['install_configure_form'] = [
      'account' => [
        'mail' => 'admin@example.com',
        // Programmatic installs expect password_confirm-style input.
        'pass' => [
          'pass1' => 'admin',
          'pass2' => 'admin',
        ],
      ],
    ];
    $install_state['interactive'] = FALSE;
    install_get_form(SiteConfigureForm::class, $install_state);
    $batch = install_profile_modules($install_state);
    $batch['operations'] = _drupal_cms_installer_prepare_tracked_operations($batch['operations']);
    batch_set($batch);
    $batch = &batch_get();
    $batch['progressive'] = FALSE;
    batch_process();
    \Drupal::state()->set('install_task', 'install_configure_form');
  }
}

chdir(dirname(__DIR__) . '/web/core');
ob_start(fn($buffer, $phase) => TRUE, 1);
include 'install.php';
